### ISSUE TITLE
MOTA metric

### ISSUE THREAD

**Issue by bitlater** [Stephlat/dataChallengePerception#1]
I don't understand, how to use MOTA metric in our task? Because as I understood the points from pose estimation in ```detections.txt``` and in ```ground_truth.txt``` are the same? Thank you.

**Comment by ragondyn** [comment]
I'm not sure to understand well what is your concern, also I will answer with a description of  the differences between 2 key metrics (MOTA/MOTP), which may be the origin of your confusion :
 
**MOTA** and **MOTP** metrics are largely used for evaluating **general** tracking problems, where the ground truth results (the goal of the inference) may be significantly **different** from the detections (the input of the algorithm). 
For example @https://arxiv.org/abs/1603.00831 is a dataset for Multiple People Tracking, based on body detections, where the detector is **really noisy** (false positives, misalignments ...) In that task, the key problem is not only to **assign a consistent ID** (Indexing problem) to each detection, but also to **remove the noise** introduced by the detector, and compute the actual position of the targets.

To put it simple, in the context of general tracking, MOTA is used to evaluate how well the **Indexing process** performs, and the MOTP how precise the **noise removal algorithm** is. Those two are not independent, if a tracker has a low precision, it is unlikely that his Re-Id process performs well.

In our challenge, because the pose estimation is reliable enough, the ground truth and detection point coordinates are almost the same (except in some rare cases, I will soon add a section in the README to explain how the ground truth file have been generated), we only use the MOTA to evaluate the **indexing consistency** of your tracker. (You still can explore the noise removal processes to improve your tracker though, if it helps you keep track of the IDs)
